### PR TITLE
Request notification permission (fixes #72)

### LINKED ISSUE #72: Deal with notification permissions on Android 12+
Android 12+ seems to require us to grant the notification permission to the app in system settings, otherwise we (sometimes!) get ForegroundServiceStartNotAllowedException. **TODO:** Check if we can request this permission from the user.

See also: https://developer.android.com/develop/ui/views/notifications/notification-permission

Starting von Android 14, we also need a foreground service type:

https://developer.android.com/about/versions/14/changes/fgs-types-required

Probably `connectedDevice`? Or maybe `shortService`, but that sounds dangerous.

Internal Sentry issue: PRETIXPRINT-ANDROID-44

### PR DESCRIPTION
**Pull request by raphaelm**

### CODE REVIEW

File: pretixprint/app/src/main/java/eu/pretix/pretixprint/ui/Settings.kt [hunk 1]
```diff
@@ -43,6 +47,7 @@ class SettingsFragment : PreferenceFragmentCompat() {
     lateinit var defaultSharedPreferences: SharedPreferences
     val types = listOf("ticket", "badge", "receipt")
     var pendingPinAction: ((pin: String) -> Unit)? = null
+    val REQUEST_CODE_NOTIFICATIONS = 19567
```
Comment (robbi5) [inline pretixprint/app/src/main/java/eu/pretix/pretixprint/ui/Settings.kt:50]: unused
